### ISSUE TITLE
Upgrade to the latest version of nodegit

### ISSUE THREAD

**Issue by jrbalsano** [edaniels/FancyMerge#3]
We're falling behind and it would be good to get up to date in case we need to pick up bug fixes in the future.

**Comment by edaniels** [comment]
![](https://media.giphy.com/media/Z0dvuZszc3r3i/giphy.gif)
![](https://49.media.tumblr.com/33b8372db58ced2ab774fbc8f123aad3/tumblr_npa1rpyY591s3y9slo1_500.gif)
