### ISSUE TITLE
Is this feature built in to GitHub now?

### ISSUE THREAD

**Issue by dpercy** [edaniels/FancyMerge#6]
Today I noticed this dropdown in the pull request UI:

![screen shot 2016-04-21 at 12 01 30 pm](https://cloud.githubusercontent.com/assets/349909/14715947/ec0642aa-07b8-11e6-9cdf-36709756ddcf.png)

Does this option make FancyMerge unnecessary?  If so maybe the README should let people know about this built-in feature.

**Comment by edaniels** [comment]
I need to figure out what exactly theirs does before claiming its built in
but I think it might be. Will get back to you on this

**Comment by edaniels** [comment]
Looks like it's the same. Updated README. Thanks @dpercy!
